# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demowidget.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1584, 1234)
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(1320, 100, 256, 192))
        self.listWidget.setObjectName("listWidget")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(1280, 340, 371, 341))
        self.groupBox.setObjectName("groupBox")
        self.horizontalSlider_liangdu = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider_liangdu.setGeometry(QtCore.QRect(80, 20, 160, 22))
        self.horizontalSlider_liangdu.setMaximum(100)
        self.horizontalSlider_liangdu.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_liangdu.setObjectName("horizontalSlider_liangdu")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 30, 54, 12))
        self.label.setObjectName("label")
        self.horizontalSlider_sedu = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider_sedu.setGeometry(QtCore.QRect(80, 50, 160, 22))
        self.horizontalSlider_sedu.setMaximum(100)
        self.horizontalSlider_sedu.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_sedu.setObjectName("horizontalSlider_sedu")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 54, 12))
        self.label_2.setObjectName("label_2")
        self.horizontalSlider_duibidu = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider_duibidu.setGeometry(QtCore.QRect(80, 80, 160, 22))
        self.horizontalSlider_duibidu.setMaximum(100)
        self.horizontalSlider_duibidu.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_duibidu.setObjectName("horizontalSlider_duibidu")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 54, 12))
        self.label_3.setObjectName("label_3")
        self.horizontalSlider_qingxidu = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider_qingxidu.setGeometry(QtCore.QRect(80, 110, 160, 22))
        self.horizontalSlider_qingxidu.setMaximum(100)
        self.horizontalSlider_qingxidu.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_qingxidu.setObjectName("horizontalSlider_qingxidu")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 120, 54, 12))
        self.label_4.setObjectName("label_4")
        self.horizontalSlider_ruidu = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider_ruidu.setGeometry(QtCore.QRect(80, 140, 160, 22))
        self.horizontalSlider_ruidu.setMaximum(100)
        self.horizontalSlider_ruidu.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_ruidu.setObjectName("horizontalSlider_ruidu")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 150, 54, 12))
        self.label_5.setObjectName("label_5")
        self.horizontalSlider_baohedu = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider_baohedu.setGeometry(QtCore.QRect(80, 170, 160, 22))
        self.horizontalSlider_baohedu.setMaximum(100)
        self.horizontalSlider_baohedu.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_baohedu.setObjectName("horizontalSlider_baohedu")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(20, 180, 54, 12))
        self.label_6.setObjectName("label_6")
        self.horizontalSlider_7 = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider_7.setGeometry(QtCore.QRect(80, 200, 160, 22))
        self.horizontalSlider_7.setMaximum(100)
        self.horizontalSlider_7.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_7.setObjectName("horizontalSlider_7")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(20, 210, 54, 12))
        self.label_7.setObjectName("label_7")
        self.spinBoxliangdu = QtWidgets.QSpinBox(self.groupBox)
        self.spinBoxliangdu.setGeometry(QtCore.QRect(260, 20, 42, 22))
        self.spinBoxliangdu.setObjectName("spinBoxliangdu")
        self.spinBox_sedu = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_sedu.setGeometry(QtCore.QRect(260, 50, 42, 22))
        self.spinBox_sedu.setObjectName("spinBox_sedu")
        self.spinBox_duibidu = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_duibidu.setGeometry(QtCore.QRect(260, 80, 42, 22))
        self.spinBox_duibidu.setObjectName("spinBox_duibidu")
        self.spinBox_baohedu = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_baohedu.setGeometry(QtCore.QRect(260, 170, 42, 22))
        self.spinBox_baohedu.setObjectName("spinBox_baohedu")
        self.spinBox_ruidu = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_ruidu.setGeometry(QtCore.QRect(260, 140, 42, 22))
        self.spinBox_ruidu.setObjectName("spinBox_ruidu")
        self.spinBox_qingxidu = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_qingxidu.setGeometry(QtCore.QRect(260, 110, 42, 22))
        self.spinBox_qingxidu.setObjectName("spinBox_qingxidu")
        self.spinBox_7 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_7.setGeometry(QtCore.QRect(260, 200, 42, 22))
        self.spinBox_7.setObjectName("spinBox_7")
        self.btnhisEqulColor1 = QtWidgets.QPushButton(self.groupBox)
        self.btnhisEqulColor1.setGeometry(QtCore.QRect(30, 240, 271, 23))
        self.btnhisEqulColor1.setObjectName("btnhisEqulColor1")
        self.btnhisEqulColor2 = QtWidgets.QPushButton(self.groupBox)
        self.btnhisEqulColor2.setGeometry(QtCore.QRect(30, 270, 271, 23))
        self.btnhisEqulColor2.setObjectName("btnhisEqulColor2")

        self.retranslateUi(Form)
        self.horizontalSlider_baohedu.valueChanged['int'].connect(self.spinBox_baohedu.setValue)
        self.horizontalSlider_liangdu.valueChanged['int'].connect(self.spinBoxliangdu.setValue)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "图像增强"))
        self.label.setText(_translate("Form", "亮度："))
        self.label_2.setText(_translate("Form", "色度："))
        self.label_3.setText(_translate("Form", "对比度："))
        self.label_4.setText(_translate("Form", "清晰度："))
        self.label_5.setText(_translate("Form", "锐度："))
        self.label_6.setText(_translate("Form", "饱和度："))
        self.label_7.setText(_translate("Form", "亮度："))
        self.btnhisEqulColor1.setText(_translate("Form", "直方图全局均衡化"))
        self.btnhisEqulColor2.setText(_translate("Form", "直方图自适应均衡化"))
