# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demowidget.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1584, 1234)
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(1210, 60, 256, 192))
        self.listWidget.setObjectName("listWidget")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(1180, 300, 331, 311))
        self.groupBox.setObjectName("groupBox")
        self.horizontalSlider_liangdu = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider_liangdu.setGeometry(QtCore.QRect(80, 20, 160, 22))
        self.horizontalSlider_liangdu.setMaximum(100)
        self.horizontalSlider_liangdu.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_liangdu.setObjectName("horizontalSlider_liangdu")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 30, 54, 12))
        self.label.setObjectName("label")
        self.horizontalSlider_sedu = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider_sedu.setGeometry(QtCore.QRect(80, 50, 160, 22))
        self.horizontalSlider_sedu.setMaximum(100)
        self.horizontalSlider_sedu.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_sedu.setObjectName("horizontalSlider_sedu")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 54, 12))
        self.label_2.setObjectName("label_2")
        self.horizontalSlider_duibidu = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider_duibidu.setGeometry(QtCore.QRect(80, 80, 160, 22))
        self.horizontalSlider_duibidu.setMaximum(100)
        self.horizontalSlider_duibidu.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_duibidu.setObjectName("horizontalSlider_duibidu")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 54, 12))
        self.label_3.setObjectName("label_3")
        self.horizontalSlider_qingxidu = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider_qingxidu.setGeometry(QtCore.QRect(80, 110, 160, 22))
        self.horizontalSlider_qingxidu.setMaximum(100)
        self.horizontalSlider_qingxidu.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_qingxidu.setObjectName("horizontalSlider_qingxidu")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 120, 54, 12))
        self.label_4.setObjectName("label_4")
        self.horizontalSlider_ruidu = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider_ruidu.setGeometry(QtCore.QRect(80, 140, 160, 22))
        self.horizontalSlider_ruidu.setMaximum(100)
        self.horizontalSlider_ruidu.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_ruidu.setObjectName("horizontalSlider_ruidu")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 150, 54, 12))
        self.label_5.setObjectName("label_5")
        self.horizontalSlider_baohedu = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider_baohedu.setGeometry(QtCore.QRect(80, 170, 160, 22))
        self.horizontalSlider_baohedu.setMaximum(100)
        self.horizontalSlider_baohedu.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_baohedu.setObjectName("horizontalSlider_baohedu")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(20, 180, 54, 12))
        self.label_6.setObjectName("label_6")
        self.horizontalSlider_7 = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider_7.setGeometry(QtCore.QRect(80, 200, 160, 22))
        self.horizontalSlider_7.setMaximum(100)
        self.horizontalSlider_7.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_7.setObjectName("horizontalSlider_7")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(20, 210, 54, 12))
        self.label_7.setObjectName("label_7")
        self.spinBoxliangdu = QtWidgets.QSpinBox(self.groupBox)
        self.spinBoxliangdu.setGeometry(QtCore.QRect(260, 20, 42, 22))
        self.spinBoxliangdu.setObjectName("spinBoxliangdu")
        self.spinBox_sedu = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_sedu.setGeometry(QtCore.QRect(260, 50, 42, 22))
        self.spinBox_sedu.setObjectName("spinBox_sedu")
        self.spinBox_duibidu = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_duibidu.setGeometry(QtCore.QRect(260, 80, 42, 22))
        self.spinBox_duibidu.setObjectName("spinBox_duibidu")
        self.spinBox_baohedu = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_baohedu.setGeometry(QtCore.QRect(260, 170, 42, 22))
        self.spinBox_baohedu.setObjectName("spinBox_baohedu")
        self.spinBox_ruidu = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_ruidu.setGeometry(QtCore.QRect(260, 140, 42, 22))
        self.spinBox_ruidu.setObjectName("spinBox_ruidu")
        self.spinBox_qingxidu = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_qingxidu.setGeometry(QtCore.QRect(260, 110, 42, 22))
        self.spinBox_qingxidu.setObjectName("spinBox_qingxidu")
        self.spinBox_7 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_7.setGeometry(QtCore.QRect(260, 200, 42, 22))
        self.spinBox_7.setObjectName("spinBox_7")
        self.btnhisEqulColor1 = QtWidgets.QPushButton(self.groupBox)
        self.btnhisEqulColor1.setGeometry(QtCore.QRect(30, 240, 271, 23))
        self.btnhisEqulColor1.setObjectName("btnhisEqulColor1")
        self.btnhisEqulColor2 = QtWidgets.QPushButton(self.groupBox)
        self.btnhisEqulColor2.setGeometry(QtCore.QRect(30, 270, 271, 23))
        self.btnhisEqulColor2.setObjectName("btnhisEqulColor2")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(1180, 630, 321, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_addnoise = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_addnoise.setGeometry(QtCore.QRect(170, 30, 121, 23))
        self.pushButton_addnoise.setObjectName("pushButton_addnoise")
        self.comboBox_zaosheng = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_zaosheng.setGeometry(QtCore.QRect(80, 30, 81, 22))
        self.comboBox_zaosheng.setObjectName("comboBox_zaosheng")
        self.comboBox_zaosheng.addItem("")
        self.comboBox_zaosheng.addItem("")
        self.pushButton_quzao = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_quzao.setGeometry(QtCore.QRect(180, 70, 111, 31))
        self.pushButton_quzao.setObjectName("pushButton_quzao")
        self.comboBox_quzao = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_quzao.setGeometry(QtCore.QRect(80, 70, 81, 21))
        self.comboBox_quzao.setObjectName("comboBox_quzao")
        self.comboBox_quzao.addItem("")
        self.comboBox_quzao.addItem("")
        self.comboBox_quzao.addItem("")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 40, 54, 12))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 70, 54, 12))
        self.label_9.setObjectName("label_9")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(1180, 760, 321, 191))
        self.groupBox_3.setObjectName("groupBox_3")
        self.comboBox_bianyuan = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_bianyuan.setGeometry(QtCore.QRect(80, 90, 91, 22))
        self.comboBox_bianyuan.setObjectName("comboBox_bianyuan")
        self.comboBox_bianyuan.addItem("")
        self.comboBox_bianyuan.addItem("")
        self.pushButton_recog = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_recog.setGeometry(QtCore.QRect(180, 150, 75, 23))
        self.pushButton_recog.setObjectName("pushButton_recog")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(20, 0, 391, 71))
        self.label_10.setTextFormat(QtCore.Qt.AutoText)
        self.label_10.setObjectName("label_10")
        self.comboBox_pinhua = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_pinhua.setGeometry(QtCore.QRect(80, 60, 91, 21))
        self.comboBox_pinhua.setObjectName("comboBox_pinhua")
        self.comboBox_pinhua.addItem("")
        self.comboBox_pinhua.addItem("")
        self.comboBox_pinhua.addItem("")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(10, 70, 54, 12))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(10, 100, 54, 12))
        self.label_12.setObjectName("label_12")

        self.retranslateUi(Form)
        self.horizontalSlider_baohedu.valueChanged['int'].connect(self.spinBox_baohedu.setValue)
        self.horizontalSlider_liangdu.valueChanged['int'].connect(self.spinBoxliangdu.setValue)
        self.spinBoxliangdu.valueChanged['int'].connect(self.horizontalSlider_liangdu.setValue)
        self.spinBox_baohedu.valueChanged['int'].connect(self.horizontalSlider_baohedu.setValue)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "图像增强"))
        self.label.setText(_translate("Form", "亮度："))
        self.label_2.setText(_translate("Form", "色度："))
        self.label_3.setText(_translate("Form", "对比度："))
        self.label_4.setText(_translate("Form", "清晰度："))
        self.label_5.setText(_translate("Form", "锐度："))
        self.label_6.setText(_translate("Form", "饱和度："))
        self.label_7.setText(_translate("Form", "亮度："))
        self.btnhisEqulColor1.setText(_translate("Form", "直方图全局均衡化"))
        self.btnhisEqulColor2.setText(_translate("Form", "直方图自适应均衡化"))
        self.groupBox_2.setTitle(_translate("Form", "图像去噪"))
        self.pushButton_addnoise.setText(_translate("Form", "添加噪声"))
        self.comboBox_zaosheng.setItemText(0, _translate("Form", "高斯噪声"))
        self.comboBox_zaosheng.setItemText(1, _translate("Form", "椒盐噪声"))
        self.pushButton_quzao.setText(_translate("Form", "去噪"))
        self.comboBox_quzao.setItemText(0, _translate("Form", "均值滤波"))
        self.comboBox_quzao.setItemText(1, _translate("Form", "高斯滤波"))
        self.comboBox_quzao.setItemText(2, _translate("Form", "中值滤波"))
        self.label_8.setText(_translate("Form", "噪声种类："))
        self.label_9.setText(_translate("Form", "去噪方法："))
        self.groupBox_3.setTitle(_translate("Form", "图像去噪/平滑边缘检测/目标识别（提取语义）"))
        self.comboBox_bianyuan.setItemText(0, _translate("Form", "canny算子"))
        self.comboBox_bianyuan.setItemText(1, _translate("Form", "sobel算子"))
        self.pushButton_recog.setText(_translate("Form", "识别"))
        self.label_10.setText(_translate("Form", "说明：主要是实现车道线检测，可使用样例图片测试"))
        self.comboBox_pinhua.setItemText(0, _translate("Form", "中值滤波"))
        self.comboBox_pinhua.setItemText(1, _translate("Form", "高斯加权滤波"))
        self.comboBox_pinhua.setItemText(2, _translate("Form", "均值滤波"))
        self.label_11.setText(_translate("Form", "图像平滑："))
        self.label_12.setText(_translate("Form", "边缘提取："))
